version = 1

[merge]
automerge_label = "auto-merge"
delete_branch_on_merge = true

[approve]
auto_approve_usernames = ["dependabot"]
auto_approve_labels = ["force-approve"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"

[merge.automerge_dependencies]
versions = ["patch", "minor"]
usernames = ["dependabot"]
