- name: "on-hold"
  color: "a04fea"
  description: "Waiting for something else"
- name: "auto-merge"
  color: "0e8a15"
  description: "Tell kodiak to merge this asap"
- name: "force-approve"
  color: "000000"
  description: "force an approval on this PR"
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
- name: "bump:patch"
  color: "edf1c1"
  description: "Publish m.y.Z - backwards compatible bugfixes"
- name: "bump:minor"
  color: "e0e4b7"
  description: "Publish x.Y.z - backwards compatible new features"
- name: "bump:major"
  color: "c9cba3"
  description: "Publish X.y.z - incompatible API changes"
- name: "patch"
  color: "efefef"
  description: "Contains backwards compatible bugfixes"
- name: "minor"
  color: "efefef"
  description: "Contains backwards compatible new features"
- name: "major"
  color: "efefef"
  description: "Contains incompatible API changes"
